FROM python:3.10

ARG UID=1000
ARG GID=1000
ARG DJANGO_USER_NAME
ARG DJANGO_USER_EMAIL
ARG DJANGO_USER_PASSWORD
ARG ENV

ENV CONTAINER_USER=server
ENV PROJECT_DIR=/home/${CONTAINER_USER}/${CONTAINER_USER}
ENV PATH="${PROJECT_DIR}/.venv/bin:$PATH:/home/${CONTAINER_USER}/.local/bin"
ENV PYTHONPATH="${PROJECT_DIR}/.venv/bin:$PYTHONPATH"
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1
ENV PIPENV_VENV_IN_PROJECT=1
ENV PIPENV_VIRTUALENV_COPIES=true
ENV PIPENV_DEFAULT_PYTHON_VERSION=3.11

RUN addgroup --gid ${GID} ${CONTAINER_USER}
RUN adduser --disabled-password --gecos '' --uid $UID --gid ${GID} ${CONTAINER_USER}

RUN mkdir -p ${PROJECT_DIR} ${PROJECT_DIR}/.venv
RUN chown -R ${CONTAINER_USER}:${CONTAINER_USER} ${PROJECT_DIR} ${PROJECT_DIR}/.venv

WORKDIR ${PROJECT_DIR}

USER ${CONTAINER_USER}

COPY --chown=${CONTAINER_USER}:${CONTAINER_USER} Pipfile* ./
RUN pip install --upgrade pip && pip install --user pipenv && pipenv install

COPY --chown=${CONTAINER_USER}:${CONTAINER_USER} setup.sh .
RUN chmod +x ./setup.sh

COPY --chown=${CONTAINER_USER}:${CONTAINER_USER} . .

ENTRYPOINT ./setup.sh
