# Generated by Django 3.2 on 2023-02-18 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='downloaded_by_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
