# Generated by Django 3.1.6 on 2021-09-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
    ]
